






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace events.tac.local.events.tac.local
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }


	}
}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Content
{


 	/// <summary>
	/// IBootstrap_Background Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content/Bootstrap Background</para>	
	/// <para>ID: 0baa039b-4d8d-4a59-bb82-05a55abc9f6e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBootstrap_BackgroundConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBootstrap_Background : IGlassBase 
	{
			
	}


	public static partial class IBootstrap_BackgroundConstants{

			public const string TemplateIdString = "0baa039b-4d8d-4a59-bb82-05a55abc9f6e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Bootstrap Background";

			

	}

	
	/// <summary>
	/// Bootstrap_Background
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content/Bootstrap Background</para>	
	/// <para>ID: 0baa039b-4d8d-4a59-bb82-05a55abc9f6e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBootstrap_BackgroundConstants.TemplateIdString)] //, Cachable = true
	public partial class Bootstrap_Background  : GlassBase, IBootstrap_Background 
	{
	   
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base
{


 	/// <summary>
	/// I_Base_Navigation Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Navigation</para>	
	/// <para>ID: 151f11ec-f894-4786-9485-5104ef4962b1</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_NavigationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Navigation : IGlassBase 
	{
			
					/// <summary>
					/// The ExcludeFromNavigation field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 92e2edb5-3f5e-4c2c-9900-bb48424216f7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_NavigationConstants.ExcludeFromNavigationFieldName)]
					bool ExcludeFromNavigation  {get; set;}
			
			
	}


	public static partial class I_Base_NavigationConstants{

			public const string TemplateIdString = "151f11ec-f894-4786-9485-5104ef4962b1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Navigation";

		
			
			public static readonly ID ExcludeFromNavigationFieldId = new ID("92e2edb5-3f5e-4c2c-9900-bb48424216f7");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
			

	}

	
	/// <summary>
	/// _Base_Navigation
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Navigation</para>	
	/// <para>ID: 151f11ec-f894-4786-9485-5104ef4962b1</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_NavigationConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Navigation  : GlassBase, I_Base_Navigation 
	{
	   
		
				/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 92e2edb5-3f5e-4c2c-9900-bb48424216f7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_NavigationConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Content
{


 	/// <summary>
	/// IBootstrap_Background_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content/Bootstrap Background Folder</para>	
	/// <para>ID: 35ff8439-1a0a-4aad-827c-25d578da245f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBootstrap_Background_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBootstrap_Background_Folder : IGlassBase 
	{
			
	}


	public static partial class IBootstrap_Background_FolderConstants{

			public const string TemplateIdString = "35ff8439-1a0a-4aad-827c-25d578da245f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Bootstrap Background Folder";

			

	}

	
	/// <summary>
	/// Bootstrap_Background_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content/Bootstrap Background Folder</para>	
	/// <para>ID: 35ff8439-1a0a-4aad-827c-25d578da245f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBootstrap_Background_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Bootstrap_Background_Folder  : GlassBase, IBootstrap_Background_Folder 
	{
	   
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Content
{


 	/// <summary>
	/// IComment Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content/Comment</para>	
	/// <para>ID: 4f7cc472-9eeb-4840-8ee4-8338bf9da5de</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentConstants.TemplateIdString )] //, Cachable = true
	public partial interface IComment : IGlassBase 
	{
			
					/// <summary>
					/// The Date field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: ac720eec-0784-4c2b-bd9c-0396d3205ccd</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.DateFieldName)]
					DateTime Date  {get; set;}
			
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 0aed0a0d-bd21-448c-9aab-25d2d1e2d44b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 77ee28e4-ff25-485e-9672-20450e34103b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.NameFieldName)]
					string Name  {get; set;}
			
			
	}


	public static partial class ICommentConstants{

			public const string TemplateIdString = "4f7cc472-9eeb-4840-8ee4-8338bf9da5de";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Comment";

		
			
			public static readonly ID DateFieldId = new ID("ac720eec-0784-4c2b-bd9c-0396d3205ccd");
			public const string DateFieldName = "Date";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("0aed0a0d-bd21-448c-9aab-25d2d1e2d44b");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID NameFieldId = new ID("77ee28e4-ff25-485e-9672-20450e34103b");
			public const string NameFieldName = "Name";
			
			

	}

	
	/// <summary>
	/// Comment
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content/Comment</para>	
	/// <para>ID: 4f7cc472-9eeb-4840-8ee4-8338bf9da5de</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentConstants.TemplateIdString)] //, Cachable = true
	public partial class Comment  : GlassBase, IComment 
	{
	   
		
				/// <summary>
				/// The Date field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: ac720eec-0784-4c2b-bd9c-0396d3205ccd</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.DateFieldName)]
				public virtual DateTime Date  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 0aed0a0d-bd21-448c-9aab-25d2d1e2d44b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 77ee28e4-ff25-485e-9672-20450e34103b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.NameFieldName)]
				public virtual string Name  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base
{


 	/// <summary>
	/// I_Base_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Content</para>	
	/// <para>ID: 57b84722-f62d-452c-9b49-45a20217b225</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_ContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Content : IGlassBase 
	{
			
					/// <summary>
					/// The ContentHeading field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ad17b597-b081-45da-a374-2d21dcdac124</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_ContentConstants.ContentHeadingFieldName)]
					string ContentHeading  {get; set;}
			
			
					/// <summary>
					/// The ContentIntro field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 4655cc09-bb00-490e-abad-a53ccf7272d6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_ContentConstants.ContentIntroFieldName)]
					string ContentIntro  {get; set;}
			
			
	}


	public static partial class I_Base_ContentConstants{

			public const string TemplateIdString = "57b84722-f62d-452c-9b49-45a20217b225";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Content";

		
			
			public static readonly ID ContentHeadingFieldId = new ID("ad17b597-b081-45da-a374-2d21dcdac124");
			public const string ContentHeadingFieldName = "ContentHeading";
			
		
			
			public static readonly ID ContentIntroFieldId = new ID("4655cc09-bb00-490e-abad-a53ccf7272d6");
			public const string ContentIntroFieldName = "ContentIntro";
			
			

	}

	
	/// <summary>
	/// _Base_Content
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Content</para>	
	/// <para>ID: 57b84722-f62d-452c-9b49-45a20217b225</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_ContentConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Content  : GlassBase, I_Base_Content 
	{
	   
		
				/// <summary>
				/// The ContentHeading field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ad17b597-b081-45da-a374-2d21dcdac124</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_ContentConstants.ContentHeadingFieldName)]
				public virtual string ContentHeading  {get; set;}
					
		
				/// <summary>
				/// The ContentIntro field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 4655cc09-bb00-490e-abad-a53ccf7272d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_ContentConstants.ContentIntroFieldName)]
				public virtual string ContentIntro  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events
{


 	/// <summary>
	/// IEvents_Section Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Events Section</para>	
	/// <para>ID: 62a32dcb-5a4d-424e-a6c7-ec53dd6c041b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEvents_SectionConstants.TemplateIdString )] //, Cachable = true
	public partial interface IEvents_Section : IGlassBase , global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Content, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Heading_Decoration, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Meta_Information, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Navigation
	{
			
	}


	public static partial class IEvents_SectionConstants{

			public const string TemplateIdString = "62a32dcb-5a4d-424e-a6c7-ec53dd6c041b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Events Section";

		
			
			public static readonly ID ContentHeadingFieldId = new ID("ad17b597-b081-45da-a374-2d21dcdac124");
			public const string ContentHeadingFieldName = "ContentHeading";
			
		
			
			public static readonly ID ContentIntroFieldId = new ID("4655cc09-bb00-490e-abad-a53ccf7272d6");
			public const string ContentIntroFieldName = "ContentIntro";
			
		
			
			public static readonly ID DecorationBannerFieldId = new ID("8eee67a7-3113-4a87-8c26-092fbca716df");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
		
			
			public static readonly ID MetaDescriptionFieldId = new ID("fcc40856-0685-440d-93ea-c4473df50b35");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("153dca69-54ab-477a-97d2-bb46b653470a");
			public const string MetaTitleFieldName = "MetaTitle";
			
		
			
			public static readonly ID RobotsFollowFieldId = new ID("536f6331-1b4e-4c56-a02e-8258de4d2b7e");
			public const string RobotsFollowFieldName = "RobotsFollow";
			
		
			
			public static readonly ID RobotsIndexFieldId = new ID("00ef2982-b6e2-4f06-aefd-ea93b5e18255");
			public const string RobotsIndexFieldName = "RobotsIndex";
			
		
			
			public static readonly ID ExcludeFromNavigationFieldId = new ID("92e2edb5-3f5e-4c2c-9900-bb48424216f7");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
			

	}

	
	/// <summary>
	/// Events_Section
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Events Section</para>	
	/// <para>ID: 62a32dcb-5a4d-424e-a6c7-ec53dd6c041b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEvents_SectionConstants.TemplateIdString)] //, Cachable = true
	public partial class Events_Section  : GlassBase, IEvents_Section 
	{
	   
		
				/// <summary>
				/// The ContentHeading field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ad17b597-b081-45da-a374-2d21dcdac124</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_SectionConstants.ContentHeadingFieldName)]
				public virtual string ContentHeading  {get; set;}
					
		
				/// <summary>
				/// The ContentIntro field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 4655cc09-bb00-490e-abad-a53ccf7272d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_SectionConstants.ContentIntroFieldName)]
				public virtual string ContentIntro  {get; set;}
					
		
				/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8eee67a7-3113-4a87-8c26-092fbca716df</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_SectionConstants.DecorationBannerFieldName)]
				public virtual Image DecorationBanner  {get; set;}
					
		
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: fcc40856-0685-440d-93ea-c4473df50b35</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_SectionConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 153dca69-54ab-477a-97d2-bb46b653470a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_SectionConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
		
				/// <summary>
				/// The RobotsFollow field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 536f6331-1b4e-4c56-a02e-8258de4d2b7e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_SectionConstants.RobotsFollowFieldName)]
				public virtual bool RobotsFollow  {get; set;}
					
		
				/// <summary>
				/// The RobotsIndex field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 00ef2982-b6e2-4f06-aefd-ea93b5e18255</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_SectionConstants.RobotsIndexFieldName)]
				public virtual bool RobotsIndex  {get; set;}
					
		
				/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 92e2edb5-3f5e-4c2c-9900-bb48424216f7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_SectionConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events
{


 	/// <summary>
	/// IEvents_List Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Events List</para>	
	/// <para>ID: 691684d0-b18c-4202-8809-cc5a686c94ae</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEvents_ListConstants.TemplateIdString )] //, Cachable = true
	public partial interface IEvents_List : IGlassBase , global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Content, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Heading_Decoration, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Meta_Information, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Navigation
	{
			
	}


	public static partial class IEvents_ListConstants{

			public const string TemplateIdString = "691684d0-b18c-4202-8809-cc5a686c94ae";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Events List";

		
			
			public static readonly ID ContentHeadingFieldId = new ID("ad17b597-b081-45da-a374-2d21dcdac124");
			public const string ContentHeadingFieldName = "ContentHeading";
			
		
			
			public static readonly ID ContentIntroFieldId = new ID("4655cc09-bb00-490e-abad-a53ccf7272d6");
			public const string ContentIntroFieldName = "ContentIntro";
			
		
			
			public static readonly ID DecorationBannerFieldId = new ID("8eee67a7-3113-4a87-8c26-092fbca716df");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
		
			
			public static readonly ID MetaDescriptionFieldId = new ID("fcc40856-0685-440d-93ea-c4473df50b35");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("153dca69-54ab-477a-97d2-bb46b653470a");
			public const string MetaTitleFieldName = "MetaTitle";
			
		
			
			public static readonly ID RobotsFollowFieldId = new ID("536f6331-1b4e-4c56-a02e-8258de4d2b7e");
			public const string RobotsFollowFieldName = "RobotsFollow";
			
		
			
			public static readonly ID RobotsIndexFieldId = new ID("00ef2982-b6e2-4f06-aefd-ea93b5e18255");
			public const string RobotsIndexFieldName = "RobotsIndex";
			
		
			
			public static readonly ID ExcludeFromNavigationFieldId = new ID("92e2edb5-3f5e-4c2c-9900-bb48424216f7");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
			

	}

	
	/// <summary>
	/// Events_List
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Events List</para>	
	/// <para>ID: 691684d0-b18c-4202-8809-cc5a686c94ae</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEvents_ListConstants.TemplateIdString)] //, Cachable = true
	public partial class Events_List  : GlassBase, IEvents_List 
	{
	   
		
				/// <summary>
				/// The ContentHeading field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ad17b597-b081-45da-a374-2d21dcdac124</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_ListConstants.ContentHeadingFieldName)]
				public virtual string ContentHeading  {get; set;}
					
		
				/// <summary>
				/// The ContentIntro field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 4655cc09-bb00-490e-abad-a53ccf7272d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_ListConstants.ContentIntroFieldName)]
				public virtual string ContentIntro  {get; set;}
					
		
				/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8eee67a7-3113-4a87-8c26-092fbca716df</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_ListConstants.DecorationBannerFieldName)]
				public virtual Image DecorationBanner  {get; set;}
					
		
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: fcc40856-0685-440d-93ea-c4473df50b35</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_ListConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 153dca69-54ab-477a-97d2-bb46b653470a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_ListConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
		
				/// <summary>
				/// The RobotsFollow field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 536f6331-1b4e-4c56-a02e-8258de4d2b7e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_ListConstants.RobotsFollowFieldName)]
				public virtual bool RobotsFollow  {get; set;}
					
		
				/// <summary>
				/// The RobotsIndex field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 00ef2982-b6e2-4f06-aefd-ea93b5e18255</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_ListConstants.RobotsIndexFieldName)]
				public virtual bool RobotsIndex  {get; set;}
					
		
				/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 92e2edb5-3f5e-4c2c-9900-bb48424216f7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvents_ListConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events
{


 	/// <summary>
	/// IEvent_Details Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Event Details</para>	
	/// <para>ID: 692e5c20-e773-42ad-a14e-499a477d35cb</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEvent_DetailsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IEvent_Details : IGlassBase , global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Content, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Content_Body, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Heading_Decoration, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Meta_Information, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Navigation
	{
			
					/// <summary>
					/// The EventImage field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 8c18669b-0218-45fa-be44-0fc87ab70b00</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IEvent_DetailsConstants.EventImageFieldName)]
					Image EventImage  {get; set;}
			
			
					/// <summary>
					/// The Highlights field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 3e54d8e8-2854-49fe-b103-a229c13615d8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IEvent_DetailsConstants.HighlightsFieldName)]
					string Highlights  {get; set;}
			
			
					/// <summary>
					/// The DifficultyLevel field.
					/// <para></para>
					/// <para>Field Type: Integer</para>		
					/// <para>Field ID: f06a2269-6f95-4d92-a8b0-9cf851bfb470</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IEvent_DetailsConstants.DifficultyLevelFieldName)]
					int DifficultyLevel  {get; set;}
			
			
					/// <summary>
					/// The Duration field.
					/// <para></para>
					/// <para>Field Type: Integer</para>		
					/// <para>Field ID: 55ee0f0a-4306-4bb3-b3af-124b081cbff0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IEvent_DetailsConstants.DurationFieldName)]
					int Duration  {get; set;}
			
			
					/// <summary>
					/// The StartDate field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 4796de68-9df7-4368-b40e-8689b1d608f5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IEvent_DetailsConstants.StartDateFieldName)]
					DateTime StartDate  {get; set;}
			
			
					/// <summary>
					/// The RelatedEvents field.
					/// <para></para>
					/// <para>Field Type: Treelist</para>		
					/// <para>Field ID: 774977b9-5f5f-4bdc-9623-c69cda788c93</para>
					/// <para>Custom Data: generic=IEvent_Details</para>
					/// </summary>
					[SitecoreField(IEvent_DetailsConstants.RelatedEventsFieldName)]
					IEnumerable<IEvent_Details> RelatedEvents  {get; set;}
			
			
					/// <summary>
					/// The Comments field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: b80dd79f-3ae5-419d-a439-24b19ac15d1f</para>
					/// <para>Custom Data: generic=Content.IComment</para>
					/// </summary>
					[SitecoreField(IEvent_DetailsConstants.CommentsFieldName)]
					IEnumerable<Content.IComment> Comments  {get; set;}
			
			
	}


	public static partial class IEvent_DetailsConstants{

			public const string TemplateIdString = "692e5c20-e773-42ad-a14e-499a477d35cb";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Event Details";

		
			
			public static readonly ID EventImageFieldId = new ID("8c18669b-0218-45fa-be44-0fc87ab70b00");
			public const string EventImageFieldName = "EventImage";
			
		
			
			public static readonly ID HighlightsFieldId = new ID("3e54d8e8-2854-49fe-b103-a229c13615d8");
			public const string HighlightsFieldName = "Highlights";
			
		
			
			public static readonly ID DifficultyLevelFieldId = new ID("f06a2269-6f95-4d92-a8b0-9cf851bfb470");
			public const string DifficultyLevelFieldName = "DifficultyLevel";
			
		
			
			public static readonly ID DurationFieldId = new ID("55ee0f0a-4306-4bb3-b3af-124b081cbff0");
			public const string DurationFieldName = "Duration";
			
		
			
			public static readonly ID StartDateFieldId = new ID("4796de68-9df7-4368-b40e-8689b1d608f5");
			public const string StartDateFieldName = "StartDate";
			
		
			
			public static readonly ID RelatedEventsFieldId = new ID("774977b9-5f5f-4bdc-9623-c69cda788c93");
			public const string RelatedEventsFieldName = "RelatedEvents";
			
		
			
			public static readonly ID CommentsFieldId = new ID("b80dd79f-3ae5-419d-a439-24b19ac15d1f");
			public const string CommentsFieldName = "Comments";
			
		
			
			public static readonly ID ContentHeadingFieldId = new ID("ad17b597-b081-45da-a374-2d21dcdac124");
			public const string ContentHeadingFieldName = "ContentHeading";
			
		
			
			public static readonly ID ContentIntroFieldId = new ID("4655cc09-bb00-490e-abad-a53ccf7272d6");
			public const string ContentIntroFieldName = "ContentIntro";
			
		
			
			public static readonly ID ContentBodyFieldId = new ID("70beac33-b8a3-4729-ae88-4589097a179a");
			public const string ContentBodyFieldName = "ContentBody";
			
		
			
			public static readonly ID DecorationBannerFieldId = new ID("8eee67a7-3113-4a87-8c26-092fbca716df");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
		
			
			public static readonly ID MetaDescriptionFieldId = new ID("fcc40856-0685-440d-93ea-c4473df50b35");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("153dca69-54ab-477a-97d2-bb46b653470a");
			public const string MetaTitleFieldName = "MetaTitle";
			
		
			
			public static readonly ID RobotsFollowFieldId = new ID("536f6331-1b4e-4c56-a02e-8258de4d2b7e");
			public const string RobotsFollowFieldName = "RobotsFollow";
			
		
			
			public static readonly ID RobotsIndexFieldId = new ID("00ef2982-b6e2-4f06-aefd-ea93b5e18255");
			public const string RobotsIndexFieldName = "RobotsIndex";
			
		
			
			public static readonly ID ExcludeFromNavigationFieldId = new ID("92e2edb5-3f5e-4c2c-9900-bb48424216f7");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
			

	}

	
	/// <summary>
	/// Event_Details
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Event Details</para>	
	/// <para>ID: 692e5c20-e773-42ad-a14e-499a477d35cb</para>	
	/// </summary>
	[SitecoreType(TemplateId=IEvent_DetailsConstants.TemplateIdString)] //, Cachable = true
	public partial class Event_Details  : GlassBase, IEvent_Details 
	{
	   
		
				/// <summary>
				/// The EventImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8c18669b-0218-45fa-be44-0fc87ab70b00</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.EventImageFieldName)]
				public virtual Image EventImage  {get; set;}
					
		
				/// <summary>
				/// The Highlights field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 3e54d8e8-2854-49fe-b103-a229c13615d8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.HighlightsFieldName)]
				public virtual string Highlights  {get; set;}
					
		
				/// <summary>
				/// The DifficultyLevel field.
				/// <para></para>
				/// <para>Field Type: Integer</para>		
				/// <para>Field ID: f06a2269-6f95-4d92-a8b0-9cf851bfb470</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.DifficultyLevelFieldName)]
				public virtual int DifficultyLevel  {get; set;}
					
		
				/// <summary>
				/// The Duration field.
				/// <para></para>
				/// <para>Field Type: Integer</para>		
				/// <para>Field ID: 55ee0f0a-4306-4bb3-b3af-124b081cbff0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.DurationFieldName)]
				public virtual int Duration  {get; set;}
					
		
				/// <summary>
				/// The StartDate field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 4796de68-9df7-4368-b40e-8689b1d608f5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.StartDateFieldName)]
				public virtual DateTime StartDate  {get; set;}
					
		
				/// <summary>
				/// The RelatedEvents field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: 774977b9-5f5f-4bdc-9623-c69cda788c93</para>
				/// <para>Custom Data: generic=IEvent_Details</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.RelatedEventsFieldName)]
				public virtual IEnumerable<IEvent_Details> RelatedEvents  {get; set;}
					
		
				/// <summary>
				/// The Comments field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: b80dd79f-3ae5-419d-a439-24b19ac15d1f</para>
				/// <para>Custom Data: generic=Content.IComment</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.CommentsFieldName)]
				public virtual IEnumerable<Content.IComment> Comments  {get; set;}
					
		
				/// <summary>
				/// The ContentHeading field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ad17b597-b081-45da-a374-2d21dcdac124</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.ContentHeadingFieldName)]
				public virtual string ContentHeading  {get; set;}
					
		
				/// <summary>
				/// The ContentIntro field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 4655cc09-bb00-490e-abad-a53ccf7272d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.ContentIntroFieldName)]
				public virtual string ContentIntro  {get; set;}
					
		
				/// <summary>
				/// The ContentBody field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 70beac33-b8a3-4729-ae88-4589097a179a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.ContentBodyFieldName)]
				public virtual string ContentBody  {get; set;}
					
		
				/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8eee67a7-3113-4a87-8c26-092fbca716df</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.DecorationBannerFieldName)]
				public virtual Image DecorationBanner  {get; set;}
					
		
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: fcc40856-0685-440d-93ea-c4473df50b35</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 153dca69-54ab-477a-97d2-bb46b653470a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
		
				/// <summary>
				/// The RobotsFollow field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 536f6331-1b4e-4c56-a02e-8258de4d2b7e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.RobotsFollowFieldName)]
				public virtual bool RobotsFollow  {get; set;}
					
		
				/// <summary>
				/// The RobotsIndex field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 00ef2982-b6e2-4f06-aefd-ea93b5e18255</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.RobotsIndexFieldName)]
				public virtual bool RobotsIndex  {get; set;}
					
		
				/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 92e2edb5-3f5e-4c2c-9900-bb48424216f7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IEvent_DetailsConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base
{


 	/// <summary>
	/// I_Base_Content_Body Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Content Body</para>	
	/// <para>ID: 7b5461c7-3f98-4cb5-9976-5123b8cf6a80</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Content_BodyConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Content_Body : IGlassBase 
	{
			
					/// <summary>
					/// The ContentBody field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 70beac33-b8a3-4729-ae88-4589097a179a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Content_BodyConstants.ContentBodyFieldName)]
					string ContentBody  {get; set;}
			
			
	}


	public static partial class I_Base_Content_BodyConstants{

			public const string TemplateIdString = "7b5461c7-3f98-4cb5-9976-5123b8cf6a80";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Content Body";

		
			
			public static readonly ID ContentBodyFieldId = new ID("70beac33-b8a3-4729-ae88-4589097a179a");
			public const string ContentBodyFieldName = "ContentBody";
			
			

	}

	
	/// <summary>
	/// _Base_Content_Body
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Content Body</para>	
	/// <para>ID: 7b5461c7-3f98-4cb5-9976-5123b8cf6a80</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Content_BodyConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Content_Body  : GlassBase, I_Base_Content_Body 
	{
	   
		
				/// <summary>
				/// The ContentBody field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 70beac33-b8a3-4729-ae88-4589097a179a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Content_BodyConstants.ContentBodyFieldName)]
				public virtual string ContentBody  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base
{


 	/// <summary>
	/// I_Base_Meta_Information Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Meta Information</para>	
	/// <para>ID: c59e2564-d5f8-4171-96ac-4db7010a6454</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Meta_InformationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Meta_Information : IGlassBase 
	{
			
					/// <summary>
					/// The MetaDescription field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: fcc40856-0685-440d-93ea-c4473df50b35</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Meta_InformationConstants.MetaDescriptionFieldName)]
					string MetaDescription  {get; set;}
			
			
					/// <summary>
					/// The MetaTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 153dca69-54ab-477a-97d2-bb46b653470a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Meta_InformationConstants.MetaTitleFieldName)]
					string MetaTitle  {get; set;}
			
			
					/// <summary>
					/// The RobotsFollow field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 536f6331-1b4e-4c56-a02e-8258de4d2b7e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Meta_InformationConstants.RobotsFollowFieldName)]
					bool RobotsFollow  {get; set;}
			
			
					/// <summary>
					/// The RobotsIndex field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 00ef2982-b6e2-4f06-aefd-ea93b5e18255</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Meta_InformationConstants.RobotsIndexFieldName)]
					bool RobotsIndex  {get; set;}
			
			
	}


	public static partial class I_Base_Meta_InformationConstants{

			public const string TemplateIdString = "c59e2564-d5f8-4171-96ac-4db7010a6454";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Meta Information";

		
			
			public static readonly ID MetaDescriptionFieldId = new ID("fcc40856-0685-440d-93ea-c4473df50b35");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("153dca69-54ab-477a-97d2-bb46b653470a");
			public const string MetaTitleFieldName = "MetaTitle";
			
		
			
			public static readonly ID RobotsFollowFieldId = new ID("536f6331-1b4e-4c56-a02e-8258de4d2b7e");
			public const string RobotsFollowFieldName = "RobotsFollow";
			
		
			
			public static readonly ID RobotsIndexFieldId = new ID("00ef2982-b6e2-4f06-aefd-ea93b5e18255");
			public const string RobotsIndexFieldName = "RobotsIndex";
			
			

	}

	
	/// <summary>
	/// _Base_Meta_Information
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Meta Information</para>	
	/// <para>ID: c59e2564-d5f8-4171-96ac-4db7010a6454</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Meta_InformationConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Meta_Information  : GlassBase, I_Base_Meta_Information 
	{
	   
		
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: fcc40856-0685-440d-93ea-c4473df50b35</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Meta_InformationConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 153dca69-54ab-477a-97d2-bb46b653470a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Meta_InformationConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
		
				/// <summary>
				/// The RobotsFollow field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 536f6331-1b4e-4c56-a02e-8258de4d2b7e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Meta_InformationConstants.RobotsFollowFieldName)]
				public virtual bool RobotsFollow  {get; set;}
					
		
				/// <summary>
				/// The RobotsIndex field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 00ef2982-b6e2-4f06-aefd-ea93b5e18255</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Meta_InformationConstants.RobotsIndexFieldName)]
				public virtual bool RobotsIndex  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base
{


 	/// <summary>
	/// I_Base_Heading_Decoration Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Heading Decoration</para>	
	/// <para>ID: ca17d967-7bbc-43ee-a9b0-0457766b76ef</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Heading_DecorationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Heading_Decoration : IGlassBase 
	{
			
					/// <summary>
					/// The DecorationBanner field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 8eee67a7-3113-4a87-8c26-092fbca716df</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Heading_DecorationConstants.DecorationBannerFieldName)]
					Image DecorationBanner  {get; set;}
			
			
	}


	public static partial class I_Base_Heading_DecorationConstants{

			public const string TemplateIdString = "ca17d967-7bbc-43ee-a9b0-0457766b76ef";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Heading Decoration";

		
			
			public static readonly ID DecorationBannerFieldId = new ID("8eee67a7-3113-4a87-8c26-092fbca716df");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
			

	}

	
	/// <summary>
	/// _Base_Heading_Decoration
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Base/_Base Heading Decoration</para>	
	/// <para>ID: ca17d967-7bbc-43ee-a9b0-0457766b76ef</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Heading_DecorationConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Heading_Decoration  : GlassBase, I_Base_Heading_Decoration 
	{
	   
		
				/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8eee67a7-3113-4a87-8c26-092fbca716df</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Heading_DecorationConstants.DecorationBannerFieldName)]
				public virtual Image DecorationBanner  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Rendering_Parameters
{


 	/// <summary>
	/// IBootstrap_Background_Color Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Rendering Parameters/Bootstrap Background Color</para>	
	/// <para>ID: ddf23463-1af2-4485-8453-7d34a9137868</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBootstrap_Background_ColorConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBootstrap_Background_Color : IGlassBase 
	{
			
					/// <summary>
					/// The CssClass field.
					/// <para></para>
					/// <para>Field Type: Droplist</para>		
					/// <para>Field ID: a01fa7d9-6b52-407f-82cc-294124db417a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBootstrap_Background_ColorConstants.CssClassFieldName)]
					string CssClass  {get; set;}
			
			
	}


	public static partial class IBootstrap_Background_ColorConstants{

			public const string TemplateIdString = "ddf23463-1af2-4485-8453-7d34a9137868";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Bootstrap Background Color";

		
			
			public static readonly ID CssClassFieldId = new ID("a01fa7d9-6b52-407f-82cc-294124db417a");
			public const string CssClassFieldName = "CssClass";
			
			

	}

	
	/// <summary>
	/// Bootstrap_Background_Color
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Rendering Parameters/Bootstrap Background Color</para>	
	/// <para>ID: ddf23463-1af2-4485-8453-7d34a9137868</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBootstrap_Background_ColorConstants.TemplateIdString)] //, Cachable = true
	public partial class Bootstrap_Background_Color  : GlassBase, IBootstrap_Background_Color 
	{
	   
		
				/// <summary>
				/// The CssClass field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// <para>Field ID: a01fa7d9-6b52-407f-82cc-294124db417a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBootstrap_Background_ColorConstants.CssClassFieldName)]
				public virtual string CssClass  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Rendering_Parameters
{


 	/// <summary>
	/// IFeatureRow_Properties Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Rendering Parameters/FeatureRow Properties</para>	
	/// <para>ID: df581877-b3cd-44a2-8c41-75e0f8f5fa8d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFeatureRow_PropertiesConstants.TemplateIdString )] //, Cachable = true
	public partial interface IFeatureRow_Properties : IGlassBase 
	{
			
					/// <summary>
					/// The ph_feature_spot_count field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d0c40914-9e32-415b-8c9d-a11bcfea47e3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFeatureRow_PropertiesConstants.Ph_Feature_Spot_CountFieldName)]
					string Ph_Feature_Spot_Count  {get; set;}
			
			
	}


	public static partial class IFeatureRow_PropertiesConstants{

			public const string TemplateIdString = "df581877-b3cd-44a2-8c41-75e0f8f5fa8d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "FeatureRow Properties";

		
			
			public static readonly ID Ph_Feature_Spot_CountFieldId = new ID("d0c40914-9e32-415b-8c9d-a11bcfea47e3");
			public const string Ph_Feature_Spot_CountFieldName = "ph_feature_spot_count";
			
			

	}

	
	/// <summary>
	/// FeatureRow_Properties
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Rendering Parameters/FeatureRow Properties</para>	
	/// <para>ID: df581877-b3cd-44a2-8c41-75e0f8f5fa8d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFeatureRow_PropertiesConstants.TemplateIdString)] //, Cachable = true
	public partial class FeatureRow_Properties  : GlassBase, IFeatureRow_Properties 
	{
	   
		
				/// <summary>
				/// The ph_feature_spot_count field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d0c40914-9e32-415b-8c9d-a11bcfea47e3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IFeatureRow_PropertiesConstants.Ph_Feature_Spot_CountFieldName)]
				public virtual string Ph_Feature_Spot_Count  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events
{


 	/// <summary>
	/// IContent_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content Page</para>	
	/// <para>ID: e866c910-08cf-4396-baf4-9522351bd394</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContent_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IContent_Page : IGlassBase , global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Content, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Content_Body, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Heading_Decoration, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Meta_Information, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Navigation
	{
			
	}


	public static partial class IContent_PageConstants{

			public const string TemplateIdString = "e866c910-08cf-4396-baf4-9522351bd394";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Content Page";

		
			
			public static readonly ID ContentHeadingFieldId = new ID("ad17b597-b081-45da-a374-2d21dcdac124");
			public const string ContentHeadingFieldName = "ContentHeading";
			
		
			
			public static readonly ID ContentIntroFieldId = new ID("4655cc09-bb00-490e-abad-a53ccf7272d6");
			public const string ContentIntroFieldName = "ContentIntro";
			
		
			
			public static readonly ID ContentBodyFieldId = new ID("70beac33-b8a3-4729-ae88-4589097a179a");
			public const string ContentBodyFieldName = "ContentBody";
			
		
			
			public static readonly ID DecorationBannerFieldId = new ID("8eee67a7-3113-4a87-8c26-092fbca716df");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
		
			
			public static readonly ID MetaDescriptionFieldId = new ID("fcc40856-0685-440d-93ea-c4473df50b35");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("153dca69-54ab-477a-97d2-bb46b653470a");
			public const string MetaTitleFieldName = "MetaTitle";
			
		
			
			public static readonly ID RobotsFollowFieldId = new ID("536f6331-1b4e-4c56-a02e-8258de4d2b7e");
			public const string RobotsFollowFieldName = "RobotsFollow";
			
		
			
			public static readonly ID RobotsIndexFieldId = new ID("00ef2982-b6e2-4f06-aefd-ea93b5e18255");
			public const string RobotsIndexFieldName = "RobotsIndex";
			
		
			
			public static readonly ID ExcludeFromNavigationFieldId = new ID("92e2edb5-3f5e-4c2c-9900-bb48424216f7");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
			

	}

	
	/// <summary>
	/// Content_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content Page</para>	
	/// <para>ID: e866c910-08cf-4396-baf4-9522351bd394</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContent_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Content_Page  : GlassBase, IContent_Page 
	{
	   
		
				/// <summary>
				/// The ContentHeading field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ad17b597-b081-45da-a374-2d21dcdac124</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.ContentHeadingFieldName)]
				public virtual string ContentHeading  {get; set;}
					
		
				/// <summary>
				/// The ContentIntro field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 4655cc09-bb00-490e-abad-a53ccf7272d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.ContentIntroFieldName)]
				public virtual string ContentIntro  {get; set;}
					
		
				/// <summary>
				/// The ContentBody field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 70beac33-b8a3-4729-ae88-4589097a179a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.ContentBodyFieldName)]
				public virtual string ContentBody  {get; set;}
					
		
				/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8eee67a7-3113-4a87-8c26-092fbca716df</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.DecorationBannerFieldName)]
				public virtual Image DecorationBanner  {get; set;}
					
		
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: fcc40856-0685-440d-93ea-c4473df50b35</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 153dca69-54ab-477a-97d2-bb46b653470a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
		
				/// <summary>
				/// The RobotsFollow field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 536f6331-1b4e-4c56-a02e-8258de4d2b7e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.RobotsFollowFieldName)]
				public virtual bool RobotsFollow  {get; set;}
					
		
				/// <summary>
				/// The RobotsIndex field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 00ef2982-b6e2-4f06-aefd-ea93b5e18255</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.RobotsIndexFieldName)]
				public virtual bool RobotsIndex  {get; set;}
					
		
				/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 92e2edb5-3f5e-4c2c-9900-bb48424216f7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContent_PageConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Content
{


 	/// <summary>
	/// IComments_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content/Comments Folder</para>	
	/// <para>ID: ef4e6dde-f73b-408b-9f46-39b459d2770b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IComments_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IComments_Folder : IGlassBase 
	{
			
	}


	public static partial class IComments_FolderConstants{

			public const string TemplateIdString = "ef4e6dde-f73b-408b-9f46-39b459d2770b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Comments Folder";

			

	}

	
	/// <summary>
	/// Comments_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Content/Comments Folder</para>	
	/// <para>ID: ef4e6dde-f73b-408b-9f46-39b459d2770b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IComments_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Comments_Folder  : GlassBase, IComments_Folder 
	{
	   
			
	}

}
namespace events.tac.local.events.tac.local.sitecore.templates.TAC.Events
{


 	/// <summary>
	/// IHome_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Home Page</para>	
	/// <para>ID: fa2e81ea-a6a9-4ed4-bc89-7e4d8e6d841d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome_Page : IGlassBase , global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Meta_Information, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Navigation, global::events.tac.local.events.tac.local.sitecore.templates.TAC.Events.Base.I_Base_Content
	{
			
	}


	public static partial class IHome_PageConstants{

			public const string TemplateIdString = "fa2e81ea-a6a9-4ed4-bc89-7e4d8e6d841d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home Page";

		
			
			public static readonly ID MetaDescriptionFieldId = new ID("fcc40856-0685-440d-93ea-c4473df50b35");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("153dca69-54ab-477a-97d2-bb46b653470a");
			public const string MetaTitleFieldName = "MetaTitle";
			
		
			
			public static readonly ID RobotsFollowFieldId = new ID("536f6331-1b4e-4c56-a02e-8258de4d2b7e");
			public const string RobotsFollowFieldName = "RobotsFollow";
			
		
			
			public static readonly ID RobotsIndexFieldId = new ID("00ef2982-b6e2-4f06-aefd-ea93b5e18255");
			public const string RobotsIndexFieldName = "RobotsIndex";
			
		
			
			public static readonly ID ExcludeFromNavigationFieldId = new ID("92e2edb5-3f5e-4c2c-9900-bb48424216f7");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
		
			
			public static readonly ID ContentHeadingFieldId = new ID("ad17b597-b081-45da-a374-2d21dcdac124");
			public const string ContentHeadingFieldName = "ContentHeading";
			
		
			
			public static readonly ID ContentIntroFieldId = new ID("4655cc09-bb00-490e-abad-a53ccf7272d6");
			public const string ContentIntroFieldName = "ContentIntro";
			
			

	}

	
	/// <summary>
	/// Home_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/TAC/Events/Home Page</para>	
	/// <para>ID: fa2e81ea-a6a9-4ed4-bc89-7e4d8e6d841d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Home_Page  : GlassBase, IHome_Page 
	{
	   
		
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: fcc40856-0685-440d-93ea-c4473df50b35</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHome_PageConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 153dca69-54ab-477a-97d2-bb46b653470a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHome_PageConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
		
				/// <summary>
				/// The RobotsFollow field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 536f6331-1b4e-4c56-a02e-8258de4d2b7e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHome_PageConstants.RobotsFollowFieldName)]
				public virtual bool RobotsFollow  {get; set;}
					
		
				/// <summary>
				/// The RobotsIndex field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 00ef2982-b6e2-4f06-aefd-ea93b5e18255</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHome_PageConstants.RobotsIndexFieldName)]
				public virtual bool RobotsIndex  {get; set;}
					
		
				/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 92e2edb5-3f5e-4c2c-9900-bb48424216f7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHome_PageConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
		
				/// <summary>
				/// The ContentHeading field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ad17b597-b081-45da-a374-2d21dcdac124</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHome_PageConstants.ContentHeadingFieldName)]
				public virtual string ContentHeading  {get; set;}
					
		
				/// <summary>
				/// The ContentIntro field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 4655cc09-bb00-490e-abad-a53ccf7272d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHome_PageConstants.ContentIntroFieldName)]
				public virtual string ContentIntro  {get; set;}
					
			
	}

}
